name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake SVGs from the contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#268AE2&color_dots=#ECE8F7,#C9B8F5,#9E00D1,#E237B9,#F0A850
            dist/github-snake-dark.svg?color_snake=#268AE2&color_dots=#1B1238,#4C28AC,#9E00D1,#E237B9,#F0A850

      - name: Push the SVGs to the "output" branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
